version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    volumes:
      - ./backend:/app
      - ./scripts:/app/scripts
      - ./tools:/app/tools
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    env_file:
      - ./backend/.env
    networks:
      - iso-control-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
    env_file:
      - ./frontend/.env
    networks:
      - iso-control-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  iso-control-network:
    driver: bridge

volumes:
  node_modules: 