apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: admin-ui
spec:
  type: NodePort
  selector:
    app: admin-ui
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 32173 