apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: admin-api
spec:
  type: NodePort
  selector:
    app: admin-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 