apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarantine-pvc-node1
  namespace: quarantine-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      kubernetes.io/hostname: node1 