apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarantine-app
  namespace: quarantine-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarantine-app
  template:
    metadata:
      labels:
        app: quarantine-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - quarantine-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: quarantine-app
          image: nginx
          volumeMounts:
            - mountPath: "/data"
              name: quarantine-storage
      volumes:
        - name: quarantine-storage
          persistentVolumeClaim:
            claimName: quarantine-pvc-node1 