apiVersion: v1
kind: Namespace
metadata:
  name: quarantine-namespace
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: quarantine-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress 