apiVersion: v1
kind: Pod
metadata:
  name: readiness-app
  labels:
    app: readiness-app
spec:
  containers:
  - name: readiness-demo
    image: busybox
    ports:
    - containerPort: 8080
    args:
    - /bin/sh
    - -c
    - |
      touch /tmp/ready;
      while true; do
        if [ -f /tmp/ready ]; then
          echo -e "HTTP/1.1 200 OK\n\nOK" | nc -l -p 8080;
        else
          sleep 5;
        fi;
      done
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-service
spec:
  selector:
    app: readiness-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080