apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: isocontrol
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /not-exist
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /not-exist
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 5
      startupProbe:
        httpGet:
          path: /not-exist
          port: 80
        failureThreshold: 10
        periodSeconds: 3