apiVersion: v1
kind: Pod
metadata:
  name: startup-app
spec:
  containers:
  - name: startup-demo
    image: busybox
    ports:
    - containerPort: 8080
    args:
    - /bin/sh
    - -c
    - |
      echo "Starting up..."; 
      sleep 30;
      touch /tmp/healthy;
      while true; do
        if [ -f /tmp/healthy ]; then
          echo "Still alive"; 
        else
          exit 1;
        fi;
        sleep 5;
      done
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 10
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 0
      periodSeconds: 5
