apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: admin-ui
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30173
      protocol: TCP 