apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: isocontrol-prod
  labels:
    app: test
spec:
  containers:
  - name: test-container
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /ready
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5 